# This file was automatically generated by passthru.fetch-deps.
# Please dont edit it manually, your changes might get overwritten!

{ fetchNuGet }:
[
  (fetchNuGet {
    pname = "Argu";
    version = "6.2.3";
    sha256 = "0lrbmki7lb5mw0gm4bm2jpqrsr26xlxmr92pvp2hsyd6yyi3c1y3";
  })
  (fetchNuGet {
    pname = "Castle.Core";
    version = "5.1.1";
    sha256 = "1caf4878nvjid3cw3rw18p9cn53brfs5x8dkvf82xvcdwc3i0nd1";
  })
  (fetchNuGet {
    pname = "coverlet.collector";
    version = "3.0.3";
    sha256 = "1igcqqr2kh6w9qx0h89y6c2zg4g2h7g8kc2lv5pz3xk6nd8iv7pw";
  })
  (fetchNuGet {
    pname = "DotNet.ReproducibleBuilds";
    version = "1.1.1";
    sha256 = "0wa0xwbwv1lzjmqwg1vq06vrpb9kkbv3xw5nq50savj0dzhqakzq";
  })
  (fetchNuGet {
    pname = "FSharp.Core";
    version = "4.3.2";
    sha256 = "1ab5vgbc1g0mab5awj6qsz16dpr5g719hg82pd86q0f39cwy7v2j";
  })
  (fetchNuGet {
    pname = "FSharp.Core";
    version = "6.0.0";
    sha256 = "1hjhvr39c1vpgrdmf8xln5q86424fqkvy9nirkr29vl2461d2039";
  })
  (fetchNuGet {
    pname = "FSharp.Core";
    version = "6.0.6";
    sha256 = "1mb1rwzs48c124pqxymnjgv6g3r6zb8n1v953hflcf20nq6yxi77";
  })
  (fetchNuGet {
    pname = "FSharpPlus";
    version = "1.6.1";
    sha256 = "0iwn91gw1qi9kqamj04sd7jn8qiqnnl8lcng9di05sp06iy32v1h";
  })
  (fetchNuGet {
    pname = "Humanizer.Core";
    version = "2.14.1";
    sha256 = "1ai7hgr0qwd7xlqfd92immddyi41j3ag91h3594yzfsgsy6yhyqi";
  })
  (fetchNuGet {
    pname = "ICSharpCode.Decompiler";
    version = "8.2.0.7535";
    sha256 = "1pvy3kss6s1v60yspfw11y3rs750rbxh735p90zrgxjshp9sq5g0";
  })
  (fetchNuGet {
    pname = "Ionide.KeepAChangelog.Tasks";
    version = "0.1.8";
    sha256 = "066zla2rp1sal6by3h3sg6ibpkk52kbhn30bzk58l6ym7q1kqa6b";
  })
  (fetchNuGet {
    pname = "Ionide.LanguageServerProtocol";
    version = "0.6.0";
    sha256 = "15wjmm91qdvhdpjjggqqsqgwlsi0wwsdzqarvdx9l1h2681hq9g0";
  })
  (fetchNuGet {
    pname = "MessagePack";
    version = "2.5.108";
    sha256 = "0cnaz28lhrdmavnxjkakl9q8p2yv8mricvp1b0wxdfnz8v41gwzs";
  })
  (fetchNuGet {
    pname = "MessagePack.Annotations";
    version = "2.5.108";
    sha256 = "0nb1fx8dwl7304kw0bc375bvlhb7pg351l4cl3vqqd7d8zqjwx5v";
  })
  (fetchNuGet {
    pname = "Microsoft.Bcl.AsyncInterfaces";
    version = "7.0.0";
    sha256 = "1waiggh3g1cclc81gmjrqbh128kwfjky3z79ma4bd2ms9pa3gvfm";
  })
  (fetchNuGet {
    pname = "Microsoft.Build";
    version = "17.9.5";
    sha256 = "176385avhnyrhcmsfg7asd95xsgcjr3cn0bfmd3pl4pk174c5z2b";
  })
  (fetchNuGet {
    pname = "Microsoft.Build.Framework";
    version = "17.9.5";
    sha256 = "1sw01fnv87bik26kfgwz1bnd4pkvbl07f6ln7q1qvj9whsljl3wq";
  })
  (fetchNuGet {
    pname = "Microsoft.Build.Locator";
    version = "1.7.8";
    sha256 = "1nxwgf3ikj5fccd3s6p8bxsvscdnymr3a109wjfv1mv24a77h5jn";
  })
  (fetchNuGet {
    pname = "Microsoft.Build.Tasks.Core";
    version = "17.3.2";
    sha256 = "1mxm6xrq4illg502kjz4l7j0vjcpfv2li9wrvf4ix9m09vdwk2jl";
  })
  (fetchNuGet {
    pname = "Microsoft.Build.Tasks.Git";
    version = "1.1.1";
    sha256 = "1bb5p4zlnfn88skkvymxfsn0jybqncl4356hwnic9jxdq2d4fz1w";
  })
  (fetchNuGet {
    pname = "Microsoft.Build.Utilities.Core";
    version = "17.3.2";
    sha256 = "0r82hrjjqpxjp3l7ncy8jdj30p7y0p1hhr1dbfrj5l3i0zxrrcj4";
  })
  (fetchNuGet {
    pname = "Microsoft.CodeAnalysis";
    version = "4.9.2";
    sha256 = "1sp8a0laq6j01n9pxnmkha71f25x86asxvvps4lyl5knpqgn8a5i";
  })
  (fetchNuGet {
    pname = "Microsoft.CodeAnalysis.Analyzers";
    version = "3.3.4";
    sha256 = "0wd6v57p53ahz5z9zg4iyzmy3src7rlsncyqpcag02jjj1yx6g58";
  })
  (fetchNuGet {
    pname = "Microsoft.CodeAnalysis.AnalyzerUtilities";
    version = "3.3.0";
    sha256 = "0b2xy6m3l1y6j2xc97cg5llia169jv4nszrrrqclh505gpw6qccz";
  })
  (fetchNuGet {
    pname = "Microsoft.CodeAnalysis.Common";
    version = "4.9.2";
    sha256 = "097lb4acla3x0m2s0w47f6321q3k2phnhpbh338d79an4b5ffks1";
  })
  (fetchNuGet {
    pname = "Microsoft.CodeAnalysis.CSharp";
    version = "4.9.2";
    sha256 = "002llvcwkaqnpzsipp9s20piw61i89spamr0wlxrvss41zh90klg";
  })
  (fetchNuGet {
    pname = "Microsoft.CodeAnalysis.CSharp.Features";
    version = "4.9.2";
    sha256 = "0n26289z9n439sn84fq4fnwcx3g7fjpzsnjx79qyig8cmy94l8zf";
  })
  (fetchNuGet {
    pname = "Microsoft.CodeAnalysis.CSharp.Workspaces";
    version = "4.9.2";
    sha256 = "0667qkwklmay77l0mzf2i3mf2jpvkg3rvdwhjg2kcp4i4sfpv711";
  })
  (fetchNuGet {
    pname = "Microsoft.CodeAnalysis.Elfie";
    version = "1.0.0";
    sha256 = "1y5r6pm9rp70xyiaj357l3gdl4i4r8xxvqllgdyrwn9gx2aqzzqk";
  })
  (fetchNuGet {
    pname = "Microsoft.CodeAnalysis.Features";
    version = "4.9.2";
    sha256 = "1ms5n24vnnq05243bhyx3hz8f74253pdi89h31zf5ya5nksq62kx";
  })
  (fetchNuGet {
    pname = "Microsoft.CodeAnalysis.Scripting.Common";
    version = "4.9.2";
    sha256 = "0g3q85v56xhgb9bz9ni2ms27g8pd8kq3mszvzs035flnckp98xbq";
  })
  (fetchNuGet {
    pname = "Microsoft.CodeAnalysis.VisualBasic";
    version = "4.9.2";
    sha256 = "0kxf70mw6wxg22ags4v43lqxpdq5q2ih485dnyiji06zbad6h4l6";
  })
  (fetchNuGet {
    pname = "Microsoft.CodeAnalysis.VisualBasic.Workspaces";
    version = "4.9.2";
    sha256 = "053lxqqn9h3qydld4k9w78a334v1qpbx6p1vcjs4mmkgy0xdvwah";
  })
  (fetchNuGet {
    pname = "Microsoft.CodeAnalysis.Workspaces.Common";
    version = "4.9.2";
    sha256 = "0p0jljwmw9pd2q63rajrnkarnsy5dsvfcnyk67wk3iq18yxqg6xa";
  })
  (fetchNuGet {
    pname = "Microsoft.CodeAnalysis.Workspaces.MSBuild";
    version = "4.9.2";
    sha256 = "154nh0830qwnh394czp65hr21dlc62qxiqi5hvfnk63a1hhsbysh";
  })
  (fetchNuGet {
    pname = "Microsoft.CodeCoverage";
    version = "17.6.3";
    sha256 = "1xxzd2yxlbq2h4k6flp7lvffmmwrjlyha2z1yvrxxymiyyggk2zg";
  })
  (fetchNuGet {
    pname = "Microsoft.DiaSymReader";
    version = "2.0.0";
    sha256 = "0g4fqxqy68bgsqzxdpz8n1sw0az1zgk33zc0xa8bwibwd1k2s6pj";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.DependencyInjection.Abstractions";
    version = "8.0.0";
    sha256 = "1zw0bpp5742jzx03wvqc8csnvsbgdqi0ls9jfc5i2vd3cl8b74pg";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Logging.Abstractions";
    version = "8.0.0";
    sha256 = "1klcqhg3hk55hb6vmjiq2wgqidsl81aldw0li2z98lrwx26msrr6";
  })
  (fetchNuGet {
    pname = "Microsoft.NET.StringTools";
    version = "17.3.2";
    sha256 = "1sg1wr7lza5c0xc4cncqr9fbsr30jlzrd1kwszr9744pfqfk1jj3";
  })
  (fetchNuGet {
    pname = "Microsoft.NET.StringTools";
    version = "17.4.0";
    sha256 = "1smx30nq22plrn2mw4wb5vfgxk6hyx12b60c4wabmpnr81lq3nzv";
  })
  (fetchNuGet {
    pname = "Microsoft.NET.StringTools";
    version = "17.9.5";
    sha256 = "0m4j7viq2ixr02yqjza2rpn9x7grfbgg3978gskbyqz2g37x5par";
  })
  (fetchNuGet {
    pname = "Microsoft.NET.Test.Sdk";
    version = "17.6.3";
    sha256 = "1f2b9ljc3l6lk2qq3ps6pzb5r4dvqvs9j1xav8kj2yy52i2dbz7r";
  })
  (fetchNuGet {
    pname = "Microsoft.NETCore.Platforms";
    version = "1.1.0";
    sha256 = "08vh1r12g6ykjygq5d3vq09zylgb84l63k49jc4v8faw9g93iqqm";
  })
  (fetchNuGet {
    pname = "Microsoft.NETCore.Platforms";
    version = "2.0.0";
    sha256 = "1fk2fk2639i7nzy58m9dvpdnzql4vb8yl8vr19r2fp8lmj9w2jr0";
  })
  (fetchNuGet {
    pname = "Microsoft.NETCore.Platforms";
    version = "5.0.0";
    sha256 = "0mwpwdflidzgzfx2dlpkvvnkgkr2ayaf0s80737h4wa35gaj11rc";
  })
  (fetchNuGet {
    pname = "Microsoft.SourceLink.AzureRepos.Git";
    version = "1.1.1";
    sha256 = "059c8i2vybprn63sw2jr7xma4yyl2syx6hzygfdpr0zd5jlgy9rz";
  })
  (fetchNuGet {
    pname = "Microsoft.SourceLink.Bitbucket.Git";
    version = "1.1.1";
    sha256 = "1p7di7lihraqisd4yfslvhpwlb9zf2casssjhyad1a0hcqmgw7n9";
  })
  (fetchNuGet {
    pname = "Microsoft.SourceLink.Common";
    version = "1.1.1";
    sha256 = "0xkdqs7az2cprar7jzjlgjpd64l6f8ixcmwmpkdm03fyb4s5m0bg";
  })
  (fetchNuGet {
    pname = "Microsoft.SourceLink.GitHub";
    version = "1.1.1";
    sha256 = "099y35f2npvva3jk1zp8hn0vb9pwm2l0ivjasdly6y2idv53s5yy";
  })
  (fetchNuGet {
    pname = "Microsoft.SourceLink.GitLab";
    version = "1.1.1";
    sha256 = "0fm50cc05fmkz77xnl6qvawkx43asdklzxhz65jnbkjp633zvx41";
  })
  (fetchNuGet {
    pname = "Microsoft.TestPlatform.ObjectModel";
    version = "17.6.3";
    sha256 = "0czzs36ybgipn9bga2swkdd653vh0wvs5hsi2lgykhblimdmb947";
  })
  (fetchNuGet {
    pname = "Microsoft.TestPlatform.TestHost";
    version = "17.6.3";
    sha256 = "0yi0n8jxf4l6v8bscgi8ws9zf5i84213pf1qj5d7nwx4jb05m23l";
  })
  (fetchNuGet {
    pname = "Microsoft.VisualStudio.Threading";
    version = "17.6.40";
    sha256 = "1iv67ndrvls7qa3wrh7mnswqbhx8ggr0w1hi7md1grfm4f0nqyz4";
  })
  (fetchNuGet {
    pname = "Microsoft.VisualStudio.Threading.Analyzers";
    version = "17.6.40";
    sha256 = "0ba9r9y3jsx3s3j190mv4gg47ibyl44s58whwvas9c64hhs4n22s";
  })
  (fetchNuGet {
    pname = "Microsoft.VisualStudio.Validation";
    version = "17.6.11";
    sha256 = "0qx4nzsx28galgzzjkgf541254d433dgxcaf7y2y1qyyxgsfjj1f";
  })
  (fetchNuGet {
    pname = "Microsoft.Win32.Registry";
    version = "5.0.0";
    sha256 = "102hvhq2gmlcbq8y2cb7hdr2dnmjzfp2k3asr1ycwrfacwyaak7n";
  })
  (fetchNuGet {
    pname = "Microsoft.Win32.SystemEvents";
    version = "6.0.0";
    sha256 = "0c6pcj088g1yd1vs529q3ybgsd2vjlk5y1ic6dkmbhvrp5jibl9p";
  })
  (fetchNuGet {
    pname = "Nerdbank.Streams";
    version = "2.10.66";
    sha256 = "04p4vd2v3mj1g315jj0fcb9ajwdr6clnbnl80mn6nyj3wmjb56nz";
  })
  (fetchNuGet {
    pname = "NETStandard.Library";
    version = "2.0.0";
    sha256 = "1bc4ba8ahgk15m8k4nd7x406nhi0kwqzbgjk2dmw52ss553xz7iy";
  })
  (fetchNuGet {
    pname = "Newtonsoft.Json";
    version = "13.0.3";
    sha256 = "0xrwysmrn4midrjal8g2hr1bbg38iyisl0svamb11arqws4w2bw7";
  })
  (fetchNuGet {
    pname = "NuGet.Frameworks";
    version = "6.5.0";
    sha256 = "0s37d1p4md0k6d4cy6sq36f2dgkd9qfbzapxhkvi8awwh0vrynhj";
  })
  (fetchNuGet {
    pname = "NUnit";
    version = "3.13.2";
    sha256 = "00bkjgarkwbj497da9d7lajala1ns67h1kx53w4bapwkf32jlcvn";
  })
  (fetchNuGet {
    pname = "NUnit3TestAdapter";
    version = "4.0.0";
    sha256 = "02z3bp1jmvzi0ags1mika9a1pb47vhq966qg262jpxzpb3v3a8fb";
  })
  (fetchNuGet {
    pname = "Serilog";
    version = "3.1.1";
    sha256 = "0ck51ndmaqflsri7yyw5792z42wsp91038rx2i6vg7z4r35vfvig";
  })
  (fetchNuGet {
    pname = "Serilog.Sinks.Async";
    version = "1.5.0";
    sha256 = "0bcb3n6lmg5wfj806mziybfmbb8gyiszrivs3swf0msy8w505gyg";
  })
  (fetchNuGet {
    pname = "Serilog.Sinks.Console";
    version = "5.0.1";
    sha256 = "0cnjjpnnhlx3k4385dbnddkz3n6khdshjix0hlv4gjmrrmjaixva";
  })
  (fetchNuGet {
    pname = "StreamJsonRpc";
    version = "2.16.36";
    sha256 = "1bwbbzd8rg1mjsig046ihs53gn8ywf5j9mjfy32axfziisqr1c2w";
  })
  (fetchNuGet {
    pname = "System.CodeDom";
    version = "6.0.0";
    sha256 = "1i55cxp8ycc03dmxx4n22qi6jkwfl23cgffb95izq7bjar8avxxq";
  })
  (fetchNuGet {
    pname = "System.Collections.Immutable";
    version = "8.0.0";
    sha256 = "0z53a42zjd59zdkszcm7pvij4ri5xbb8jly9hzaad9khlf69bcqp";
  })
  (fetchNuGet {
    pname = "System.Composition";
    version = "8.0.0";
    sha256 = "0y7rp5qwwvh430nr0r15zljw01gny8yvr0gg6w5cmsk3q7q7a3dc";
  })
  (fetchNuGet {
    pname = "System.Composition.AttributedModel";
    version = "8.0.0";
    sha256 = "16j61piz1jf8hbh14i1i4m2r9vw79gdqhjr4f4i588h52249fxlz";
  })
  (fetchNuGet {
    pname = "System.Composition.Convention";
    version = "8.0.0";
    sha256 = "10fwp7692a6yyw1p8b923k061zh95a6xs3vzfdmdv5pmf41cxlb7";
  })
  (fetchNuGet {
    pname = "System.Composition.Hosting";
    version = "8.0.0";
    sha256 = "1gbfimhxx6v6073pblv4rl5shz3kgx8lvfif5db26ak8pl5qj4kb";
  })
  (fetchNuGet {
    pname = "System.Composition.Runtime";
    version = "8.0.0";
    sha256 = "0snljpgfmg0wlkwilkvn9qjjghq1pjdfgdpnwhvl2qw6vzdij703";
  })
  (fetchNuGet {
    pname = "System.Composition.TypedParts";
    version = "8.0.0";
    sha256 = "0skwla26d8clfz3alr8m42qbzsrbi7dhg74z6ha832b6730mm4pr";
  })
  (fetchNuGet {
    pname = "System.Configuration.ConfigurationManager";
    version = "4.4.0";
    sha256 = "1hjgmz47v5229cbzd2pwz2h0dkq78lb2wp9grx8qr72pb5i0dk7v";
  })
  (fetchNuGet {
    pname = "System.Configuration.ConfigurationManager";
    version = "4.5.0";
    sha256 = "1frpy24mn6q7hgwayj98kkx89z861f5dmia4j6zc0a2ydgx8x02c";
  })
  (fetchNuGet {
    pname = "System.Configuration.ConfigurationManager";
    version = "6.0.0";
    sha256 = "0sqapr697jbb4ljkq46msg0xx1qpmc31ivva6llyz2wzq3mpmxbw";
  })
  (fetchNuGet {
    pname = "System.Configuration.ConfigurationManager";
    version = "8.0.0";
    sha256 = "08dadpd8lx6x7craw3h3444p7ncz4wk0a3j1681lyhhd56ln66f6";
  })
  (fetchNuGet {
    pname = "System.Data.DataSetExtensions";
    version = "4.5.0";
    sha256 = "0gk9diqx388qjmbhljsx64b5i0p9cwcaibd4h7f8x901pz84x6ma";
  })
  (fetchNuGet {
    pname = "System.Diagnostics.DiagnosticSource";
    version = "7.0.2";
    sha256 = "1h97ikph775gya93qsjjaka87qcygbyh1064rh1hnfcnp5xv0ipi";
  })
  (fetchNuGet {
    pname = "System.Diagnostics.EventLog";
    version = "6.0.0";
    sha256 = "08y1x2d5w2hnhkh9r1998pjc7r4qp0rmzax062abha85s11chifd";
  })
  (fetchNuGet {
    pname = "System.Diagnostics.EventLog";
    version = "8.0.0";
    sha256 = "1xnvcidh2qf6k7w8ij1rvj0viqkq84cq47biw0c98xhxg5rk3pxf";
  })
  (fetchNuGet {
    pname = "System.Drawing.Common";
    version = "6.0.0";
    sha256 = "02n8rzm58dac2np8b3xw8ychbvylja4nh6938l5k2fhyn40imlgz";
  })
  (fetchNuGet {
    pname = "System.Formats.Asn1";
    version = "6.0.0";
    sha256 = "1vvr7hs4qzjqb37r0w1mxq7xql2b17la63jwvmgv65s1hj00g8r9";
  })
  (fetchNuGet {
    pname = "System.IO.Pipelines";
    version = "7.0.0";
    sha256 = "1ila2vgi1w435j7g2y7ykp2pdbh9c5a02vm85vql89az93b7qvav";
  })
  (fetchNuGet {
    pname = "System.IO.Pipelines";
    version = "8.0.0";
    sha256 = "00f36lqz1wf3x51kwk23gznkjjrf5nmqic9n7073nhrgrvb43nid";
  })
  (fetchNuGet {
    pname = "System.Memory";
    version = "4.5.5";
    sha256 = "08jsfwimcarfzrhlyvjjid61j02irx6xsklf32rv57x2aaikvx0h";
  })
  (fetchNuGet {
    pname = "System.Reflection.Metadata";
    version = "1.6.0";
    sha256 = "1wdbavrrkajy7qbdblpbpbalbdl48q3h34cchz24gvdgyrlf15r4";
  })
  (fetchNuGet {
    pname = "System.Reflection.Metadata";
    version = "6.0.0";
    sha256 = "1x0b289r9yjzdqypi2x3dc8sa66s3b6bpc7l2f8hxrzl6czdg4al";
  })
  (fetchNuGet {
    pname = "System.Reflection.Metadata";
    version = "8.0.0";
    sha256 = "10a8vm0c3n5cili5nix6bdmiaxr69qisvk356pb81f2s8bgq40bm";
  })
  (fetchNuGet {
    pname = "System.Reflection.MetadataLoadContext";
    version = "8.0.0";
    sha256 = "0jicnjqk3823w30pp4nr9nnlrfakz894pjsr4j18v3c7k0ymfbld";
  })
  (fetchNuGet {
    pname = "System.Resources.Extensions";
    version = "6.0.0";
    sha256 = "1h73gps9ffw77vys4zwgm78fgackqw6a7rjrg75mmx79vdw1shgw";
  })
  (fetchNuGet {
    pname = "System.Runtime.CompilerServices.Unsafe";
    version = "6.0.0";
    sha256 = "0qm741kh4rh57wky16sq4m0v05fxmkjjr87krycf5vp9f0zbahbc";
  })
  (fetchNuGet {
    pname = "System.Security.AccessControl";
    version = "4.5.0";
    sha256 = "1wvwanz33fzzbnd2jalar0p0z3x0ba53vzx1kazlskp7pwyhlnq0";
  })
  (fetchNuGet {
    pname = "System.Security.AccessControl";
    version = "5.0.0";
    sha256 = "17n3lrrl6vahkqmhlpn3w20afgz09n7i6rv0r3qypngwi7wqdr5r";
  })
  (fetchNuGet {
    pname = "System.Security.AccessControl";
    version = "6.0.0";
    sha256 = "0a678bzj8yxxiffyzy60z2w1nczzpi8v97igr4ip3byd2q89dv58";
  })
  (fetchNuGet {
    pname = "System.Security.Cryptography.Pkcs";
    version = "6.0.1";
    sha256 = "0wswhbvm3gh06azg9k1zfvmhicpzlh7v71qzd4x5zwizq4khv7iq";
  })
  (fetchNuGet {
    pname = "System.Security.Cryptography.ProtectedData";
    version = "4.4.0";
    sha256 = "1q8ljvqhasyynp94a1d7jknk946m20lkwy2c3wa8zw2pc517fbj6";
  })
  (fetchNuGet {
    pname = "System.Security.Cryptography.ProtectedData";
    version = "4.5.0";
    sha256 = "11qlc8q6b7xlspayv07718ibzvlj6ddqqxkvcbxv5b24d5kzbrb7";
  })
  (fetchNuGet {
    pname = "System.Security.Cryptography.ProtectedData";
    version = "6.0.0";
    sha256 = "05kd3a8w7658hjxq9vvszxip30a479fjmfq4bq1r95nrsvs4hbss";
  })
  (fetchNuGet {
    pname = "System.Security.Cryptography.ProtectedData";
    version = "8.0.0";
    sha256 = "1ysjx3b5ips41s32zacf4vs7ig41906mxrsbmykdzi0hvdmjkgbx";
  })
  (fetchNuGet {
    pname = "System.Security.Cryptography.Xml";
    version = "6.0.0";
    sha256 = "0aybd4mp9f8d4kgdnrnad7bmdg872044p75nk37f8a4lvkh2sywd";
  })
  (fetchNuGet {
    pname = "System.Security.Permissions";
    version = "4.5.0";
    sha256 = "192ww5rm3c9mirxgl1nzyrwd18am3izqls0hzm0fvcdjl5grvbhm";
  })
  (fetchNuGet {
    pname = "System.Security.Permissions";
    version = "6.0.0";
    sha256 = "0jsl4xdrkqi11iwmisi1r2f2qn5pbvl79mzq877gndw6ans2zhzw";
  })
  (fetchNuGet {
    pname = "System.Security.Principal.Windows";
    version = "4.5.0";
    sha256 = "0rmj89wsl5yzwh0kqjgx45vzf694v9p92r4x4q6yxldk1cv1hi86";
  })
  (fetchNuGet {
    pname = "System.Security.Principal.Windows";
    version = "5.0.0";
    sha256 = "1mpk7xj76lxgz97a5yg93wi8lj0l8p157a5d50mmjy3gbz1904q8";
  })
  (fetchNuGet {
    pname = "System.Text.Encodings.Web";
    version = "7.0.0";
    sha256 = "1151hbyrcf8kyg1jz8k9awpbic98lwz9x129rg7zk1wrs6vjlpxl";
  })
  (fetchNuGet {
    pname = "System.Text.Encodings.Web";
    version = "8.0.0";
    sha256 = "1wbypkx0m8dgpsaqgyywz4z760xblnwalb241d5qv9kx8m128i11";
  })
  (fetchNuGet {
    pname = "System.Text.Json";
    version = "7.0.3";
    sha256 = "0zjrnc9lshagm6kdb9bdh45dmlnkpwcpyssa896sda93ngbmj8k9";
  })
  (fetchNuGet {
    pname = "System.Text.Json";
    version = "8.0.0";
    sha256 = "134savxw0sq7s448jnzw17bxcijsi1v38mirpbb6zfxmqlf04msw";
  })
  (fetchNuGet {
    pname = "System.Threading.Channels";
    version = "8.0.0";
    sha256 = "060ab3gxgmffzlfcj08hpmkyfkhyiky9brw35klbl32pnfhdi53k";
  })
  (fetchNuGet {
    pname = "System.Threading.Tasks.Dataflow";
    version = "6.0.0";
    sha256 = "1b4vyjdir9kdkiv2fqqm4f76h0df68k8gcd7jb2b38zgr2vpnk3c";
  })
  (fetchNuGet {
    pname = "System.Threading.Tasks.Dataflow";
    version = "7.0.0";
    sha256 = "0ham9l8xrmlq2qwin53n82iz1wanci2h695i3cq83jcw4n28qdr9";
  })
  (fetchNuGet {
    pname = "System.Threading.Tasks.Dataflow";
    version = "8.0.0";
    sha256 = "02mmqnbd7ybin1yiffrq3ph71rsbrnf6r6m01j98ynydqfscz9s3";
  })
  (fetchNuGet {
    pname = "System.Threading.Tasks.Extensions";
    version = "4.5.4";
    sha256 = "0y6ncasgfcgnjrhynaf0lwpkpkmv4a07sswwkwbwb5h7riisj153";
  })
  (fetchNuGet {
    pname = "System.Windows.Extensions";
    version = "6.0.0";
    sha256 = "1wy9pq9vn1bqg5qnv53iqrbx04yzdmjw4x5yyi09y3459vaa1sip";
  })
]
